version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: daily}
    labels:
      -  Robot
      - 完 Upkeep

  - package-ecosystem: pip
    directory: /
    schedule: {interval: daily}
    labels:
      -  Robot
      - 完 Upkeep
