version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: daily}
    commit-message: {prefix: â¬†ï¸}
    labels:
      - ğŸ¤– Robot
      - ğŸ§¹ Upkeep

  # NB: a custom dependency upgrade workflow is under workflows/upgrade.yml
